// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXQfKV_vEXEKqcNv5nbMfRBVktBQ-iunk',
    appId: '1:625132868638:web:5483234636af622bc08a0f',
    messagingSenderId: '625132868638',
    projectId: 'libraryhaven-ef8ec',
    authDomain: 'libraryhaven-ef8ec.firebaseapp.com',
    storageBucket: 'libraryhaven-ef8ec.firebasestorage.app',
    measurementId: 'G-6BV0QKLH22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKC6gef42qBvh4AQL5f4pteKBemwhDY3Q',
    appId: '1:625132868638:android:97fe2f809f47f046c08a0f',
    messagingSenderId: '625132868638',
    projectId: 'libraryhaven-ef8ec',
    storageBucket: 'libraryhaven-ef8ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSqx9l-PENRUihn-iVoX5mVNwifhWM78A',
    appId: '1:625132868638:ios:c35aa4835c3bc7b1c08a0f',
    messagingSenderId: '625132868638',
    projectId: 'libraryhaven-ef8ec',
    storageBucket: 'libraryhaven-ef8ec.firebasestorage.app',
    iosBundleId: 'com.example.libraryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSqx9l-PENRUihn-iVoX5mVNwifhWM78A',
    appId: '1:625132868638:ios:c35aa4835c3bc7b1c08a0f',
    messagingSenderId: '625132868638',
    projectId: 'libraryhaven-ef8ec',
    storageBucket: 'libraryhaven-ef8ec.firebasestorage.app',
    iosBundleId: 'com.example.libraryapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXQfKV_vEXEKqcNv5nbMfRBVktBQ-iunk',
    appId: '1:625132868638:web:1898ab6bc0f2876ec08a0f',
    messagingSenderId: '625132868638',
    projectId: 'libraryhaven-ef8ec',
    authDomain: 'libraryhaven-ef8ec.firebaseapp.com',
    storageBucket: 'libraryhaven-ef8ec.firebasestorage.app',
    measurementId: 'G-FGHBLZJ47H',
  );
}
